version: 2
updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: monthly
    day: sunday
    time: "04:00"
    timezone: America/Vancouver
  open-pull-requests-limit: 10
- package-ecosystem: github-actions
  directory: '/'
  schedule:
    interval: monthly
    day: sunday
    time: "04:00"
    timezone: PST8PDT
  open-pull-requests-limit: 10
